baseURL = "https://kaiseiyokoyama.github.io/blog/"
author = "Kaisei Yokoyama"
title = "モダンな言語をたのむ"
canonifyurls = true
publishDir = "docs"
theme = "hugo_theme_pickles"
hasCJKLanguage = true
languageCode = "ja-jp"
copyright = "&copy; Kaisei Yokoyama"
pygmentsCodeFences = true

[params]
  twitter = "KaiseiYokoyama"
  github = "KaiseiYokoyama"